services:
  proxy:
    image: nginx:1.29
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tugas1docker
  wp:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - tugas1docker
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - tugas1docker
  pma:
    image: phpmyadmin
    environment:
      - PMA_ABSOLUTE_URI=/pma/
    networks:
      - tugas1docker
volumes:
  wordpress:
networks:
  tugas1docker:
    driver: bridge
